services:
  parser:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PORT=${PORT}
    volumes:
      - ./tmp:/app/tmp
    networks:
      - shared-network
    restart: unless-stopped

networks:
  shared-network:
    external: true