services:
  mongodb:
    image: mongo:latest
    container_name: shared-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - shared-network
    restart: unless-stopped
    command: ["--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'shared-mongodb:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30

  redis:
    image: redis:alpine
    container_name: shared-redis
    ports:
      - "6379:6379"
    networks:
      - shared-network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  shared-network:
    name: shared-network